### ISSUE TITLE
Assignments (TO BE DECIDED)

### ISSUE THREAD

**Issue by Taki21** [OperatingSytemDevs/UnnamedOS#1]
@Ad5001 - 

@AmiroEmad - 

@ImagicalGamer - 

@PocketKiller -

@remotevase - 

@Taki21 - Graphics? Idk...

@TheDragonRing -

**Comment by Taki21** [comment]
#2

**Comment by AmiroEmad** [comment]
what coding language are we going to learn to make this thing

and how i are we going to refer our code to run things up

and also pocketkiller is wrong he is now @ipocket also he is inactive

**Comment by remotevase** [comment]
I don't have time for dis, and this project includes me learning a new coding language, anther thing that I don't have time to do. php, HTML. That's all I can help with. Unless your count coming up with ideas as a job... I'm great at ideas, just sucky at executing them 😛

**Comment by TheDragonRing** [comment]
I think I agree with @remotevase :P

**Comment by TheDragonRing** [comment]
Oops, clicked the wrong button :/

**Comment by Taki21** [comment]
Ok .

**Comment by AmiroEmad** [comment]
taki please invite @lancemoheb to the org he is my friend but i am not responsible for anything wrong or good he do as i didn't code with him before but he is trusted don't worry

**Comment by remotevase** [comment]
that user doesn't exist

**Comment by Dog2puppy** [comment]
What's the Lang? If it's Binary I'm out for sure. I do
-Lua
-PHP
-C#
-JS
-Some Java

**Comment by Taki21** [comment]
C# yes thx

**Comment by Taki21** [comment]
@Dog2puppy has been invited! https://github.com/OperatingSytemDevs

**Comment by Dog2puppy** [comment]
I love C#. Used it for a Discord bot once. Lost it all when my laptop died. :(

**Comment by developerCodex** [comment]
Hey, I'd be willing to join I have made tons of Discord bots with javascript, I know a bit of C#

**Comment by Taki21** [comment]
Ok U will be added thx for joining!

**Comment by Taki21** [comment]
Welcome @developerCodex https://github.com/OperatingSytemDevs

**Comment by Taki21** [comment]
#3
